#!/bin/sh
# shellcheck disable=SC1091
. "$CONFIG_DIR/colors.sh"
. "$CONFIG_DIR/icons.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"

############## BAR ##############
sketchybar --bar \
    height=44 \
    position=top \
    sticky=on \
    padding_left=12 \
    padding_right=12 \
    color="$BAR_COLOR" \
    border_width=1 \
    border_color="$BAR_BORDER_COLOR" \
    notch_width=200 \
    display=all \
    topmost=window

############## DEFAULTS ##############
sketchybar --default \
    padding_left=6 \
    padding_right=6 \
    icon.font="Symbols Nerd Font Mono:Regular:14.0" \
    icon.color="$ICON_COLOR" \
    label.font="JetBrains Mono:Regular:13.0" \
    label.color="$LABEL_COLOR" \
    icon.padding_right=4 \
    background.corner_radius=4 \
    background.height=22

############## ITEMS ##############

# Discord badge (left)
sketchybar --add item discord left \
    --set discord \
        drawing=off \
        icon="$ICON_DISCORD" \
        icon.color="$RED" \
        label.color="$RED" \
        update_freq=5 \
        script="$PLUGIN_DIR/discord.sh" \
    --subscribe discord system_woke

# Slack badge (left)
sketchybar --add item slack left \
    --set slack \
        drawing=off \
        icon="$ICON_SLACK" \
        icon.color="$ACCENT_COLOR" \
        label.color="$ACCENT_COLOR" \
        update_freq=5 \
        script="$PLUGIN_DIR/slack.sh" \
    --subscribe slack system_woke

# Telegram badge (left)
sketchybar --add item telegram left \
    --set telegram \
        drawing=off \
        icon="$ICON_TELEGRAM" \
        icon.color="$BLUE" \
        label.color="$BLUE" \
        update_freq=5 \
        script="$PLUGIN_DIR/telegram.sh" \
    --subscribe telegram system_woke

# Notification badge bracket
sketchybar --add bracket notifications discord slack telegram \
    --set notifications \
        background.color="$BAR_BORDER_COLOR" \
        background.corner_radius=4 \
        background.height=28 \
        background.drawing=on

# Now Playing (left) - any media source
sketchybar --add item nowplaying left \
    --set nowplaying \
        drawing=off \
        update_freq=5 \
        script="$PLUGIN_DIR/nowplaying.sh"

# Now Playing progress bar (left)
sketchybar --add item nowplaying_progress left \
    --set nowplaying_progress \
        drawing=off \
        label.font="JetBrains Mono:Regular:8.0" \
        label.color="$ACCENT_COLOR" \
        padding_left=0 \
        padding_right=4

# Clock (right) - far left of right group
sketchybar --add item clock right \
    --set clock \
        icon="$ICON_CLOCK" \
        update_freq=10 \
        script="$PLUGIN_DIR/time.sh"

# Date (right)
sketchybar --add item date right \
    --set date \
        icon="$ICON_CALENDAR" \
        update_freq=60 \
        script="$PLUGIN_DIR/time.sh"

# Battery (right)
sketchybar --add item battery right \
    --set battery \
        update_freq=60 \
        script="$PLUGIN_DIR/battery.sh"

# Weather (right)
sketchybar --add item weather right \
    --set weather \
        drawing=off \
        update_freq=1800 \
        script="$PLUGIN_DIR/weather.sh"

# CPU + RAM (right)
sketchybar --add item cpu right \
    --set cpu \
        icon="$ICON_CPU" \
        update_freq=5 \
        script="$PLUGIN_DIR/cpu.sh"

# Media indicator - mic/camera in use (right)
sketchybar --add item media_indicator right \
    --set media_indicator \
        drawing=off \
        icon="$ICON_MIC" \
        icon.color="$RED" \
        update_freq=5 \
        script="$PLUGIN_DIR/media_indicator.sh"

############## FINALISE ##############
sketchybar --update
